# .streamlit/config.toml

[theme]
primaryColor="#f63366"      # Primary color for interactive widgets
backgroundColor="#FFFFFF"   # Main background color
secondaryBackgroundColor="#F0F2F6" # Secondary background color (e.g., sidebar)
textColor="#262730"         # Text color
font="sans serif"
